id: P4F9408FE
initial_creation_type: input
source_metadata:
  Title: Mahāyāna-sūtra-saṃgrahaḥ ( part 1)
  Editor: Vaidya, P.L
  Publisher: The Mithila Institute of Post-Graduate Studies and Research in Sanskrit
    Learning
  Place of Publication: Darbhanga
  Year: '1961'
  1 nidānaparivartaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  2 ānandaparivarto dvitīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  3 tathatāparivartastṛtīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  4 aupamyaparivartaścaturthaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  5 subhūtiparivartaḥ pañcamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  6 caryāparivartaḥ ṣaṣṭhaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  7 anuśaṃsāparivartaḥ saptamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:11:52.659031'
last_modified_at: '2022-03-08T16:11:52.659040'
